### PR TITLE
guys. we're going to remember to do a twerking class.

### PR DESCRIPTION
**Pull request by ashleyyy**

### CODE REVIEW

**Comment by li3n3** [comment]
are we still counting the Monday that is no longer a holiday in Oregon and that no one seems to be around for as of this past year  ;_;

**Comment by ashleyyy** [comment]
The Canadians are traditionally still around, since it's a holiday for us. Surely we count?

**Comment by li3n3** [comment]
EXTREMELY. I will set my sights on the Canadians this year. I can rely on the Canadians.

**Comment by notjes5199** [comment]
it's still a holiday for those of us who are employed by Californians, too. and in 45 other states.

**Comment by jes5199** [comment]
it's still a holiday for those of us employed by Californians. and for people in 45 other states of the union

**Comment by outofculture** [comment]
Which Kevin?

**Comment by li3n3** [comment]
okay I am just gonna need all y'all non-Oregonians to be visible in the future, because this last year I felt like a great big silly for being like "but Monday plans; are there any" and everyone looked at me like I had three heads

for certain values of "everyone"

**Comment by jes5199** [comment]
the real Kevin

**Comment by li3n3** [comment]
is there twerking, though

**Comment by keturn** [comment]
Monday morning, Om Movement Center, ~10 AM? (announcement with exact time & other details forthcoming)

**Pull request closed without merging**
